# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.com/platform/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: conf.py

# Activer l'exportation automatique au format PDF sur Read the Docs
formats:
  - pdf
